###################################################################

# Created by write_sdc on Sun Dec  1 04:36:49 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current A
set_wire_load_mode top
set_wire_load_model -name tsmcwire -library lec25dscc25_TT
set_driving_cell -min -lib_cell dffacs1 [get_ports rst_n]
set_driving_cell -lib_cell dffacs1 [get_ports in_vld]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[63]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[62]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[61]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[60]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[59]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[58]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[57]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[56]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[55]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[54]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[53]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[52]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[51]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[50]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[49]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[48]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[47]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[46]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[45]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[44]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[43]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[42]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[41]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[40]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[39]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[38]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[37]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[36]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[35]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[34]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[33]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[32]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[31]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[30]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[29]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[28]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[27]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[26]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[25]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[24]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[23]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[22]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[21]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[20]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[19]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[18]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[17]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[16]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[15]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[14]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[13]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[12]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[11]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[10]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[9]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[8]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[7]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[6]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[5]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[4]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[3]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[2]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[1]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mcand[0]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[63]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[62]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[61]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[60]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[59]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[58]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[57]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[56]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[55]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[54]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[53]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[52]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[51]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[50]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[49]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[48]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[47]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[46]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[45]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[44]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[43]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[42]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[41]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[40]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[39]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[38]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[37]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[36]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[35]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[34]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[33]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[32]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[31]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[30]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[29]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[28]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[27]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[26]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[25]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[24]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[23]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[22]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[21]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[20]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[19]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[18]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[17]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[16]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[15]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[14]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[13]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[12]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[11]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[10]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[9]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[8]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[7]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[6]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[5]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[4]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[3]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[2]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[1]}]
set_driving_cell -lib_cell dffacs1 [get_ports {mplier[0]}]
set_driving_cell -lib_cell dffacs1 [get_ports out_rdy]
set_fanout_load 10 [get_ports in_rdy]
set_fanout_load 10 [get_ports {product[63]}]
set_fanout_load 10 [get_ports {product[62]}]
set_fanout_load 10 [get_ports {product[61]}]
set_fanout_load 10 [get_ports {product[60]}]
set_fanout_load 10 [get_ports {product[59]}]
set_fanout_load 10 [get_ports {product[58]}]
set_fanout_load 10 [get_ports {product[57]}]
set_fanout_load 10 [get_ports {product[56]}]
set_fanout_load 10 [get_ports {product[55]}]
set_fanout_load 10 [get_ports {product[54]}]
set_fanout_load 10 [get_ports {product[53]}]
set_fanout_load 10 [get_ports {product[52]}]
set_fanout_load 10 [get_ports {product[51]}]
set_fanout_load 10 [get_ports {product[50]}]
set_fanout_load 10 [get_ports {product[49]}]
set_fanout_load 10 [get_ports {product[48]}]
set_fanout_load 10 [get_ports {product[47]}]
set_fanout_load 10 [get_ports {product[46]}]
set_fanout_load 10 [get_ports {product[45]}]
set_fanout_load 10 [get_ports {product[44]}]
set_fanout_load 10 [get_ports {product[43]}]
set_fanout_load 10 [get_ports {product[42]}]
set_fanout_load 10 [get_ports {product[41]}]
set_fanout_load 10 [get_ports {product[40]}]
set_fanout_load 10 [get_ports {product[39]}]
set_fanout_load 10 [get_ports {product[38]}]
set_fanout_load 10 [get_ports {product[37]}]
set_fanout_load 10 [get_ports {product[36]}]
set_fanout_load 10 [get_ports {product[35]}]
set_fanout_load 10 [get_ports {product[34]}]
set_fanout_load 10 [get_ports {product[33]}]
set_fanout_load 10 [get_ports {product[32]}]
set_fanout_load 10 [get_ports {product[31]}]
set_fanout_load 10 [get_ports {product[30]}]
set_fanout_load 10 [get_ports {product[29]}]
set_fanout_load 10 [get_ports {product[28]}]
set_fanout_load 10 [get_ports {product[27]}]
set_fanout_load 10 [get_ports {product[26]}]
set_fanout_load 10 [get_ports {product[25]}]
set_fanout_load 10 [get_ports {product[24]}]
set_fanout_load 10 [get_ports {product[23]}]
set_fanout_load 10 [get_ports {product[22]}]
set_fanout_load 10 [get_ports {product[21]}]
set_fanout_load 10 [get_ports {product[20]}]
set_fanout_load 10 [get_ports {product[19]}]
set_fanout_load 10 [get_ports {product[18]}]
set_fanout_load 10 [get_ports {product[17]}]
set_fanout_load 10 [get_ports {product[16]}]
set_fanout_load 10 [get_ports {product[15]}]
set_fanout_load 10 [get_ports {product[14]}]
set_fanout_load 10 [get_ports {product[13]}]
set_fanout_load 10 [get_ports {product[12]}]
set_fanout_load 10 [get_ports {product[11]}]
set_fanout_load 10 [get_ports {product[10]}]
set_fanout_load 10 [get_ports {product[9]}]
set_fanout_load 10 [get_ports {product[8]}]
set_fanout_load 10 [get_ports {product[7]}]
set_fanout_load 10 [get_ports {product[6]}]
set_fanout_load 10 [get_ports {product[5]}]
set_fanout_load 10 [get_ports {product[4]}]
set_fanout_load 10 [get_ports {product[3]}]
set_fanout_load 10 [get_ports {product[2]}]
set_fanout_load 10 [get_ports {product[1]}]
set_fanout_load 10 [get_ports {product[0]}]
set_fanout_load 10 [get_ports out_vld]
set_load -pin_load 0.1 [get_ports in_rdy]
set_load -pin_load 0.1 [get_ports {product[63]}]
set_load -pin_load 0.1 [get_ports {product[62]}]
set_load -pin_load 0.1 [get_ports {product[61]}]
set_load -pin_load 0.1 [get_ports {product[60]}]
set_load -pin_load 0.1 [get_ports {product[59]}]
set_load -pin_load 0.1 [get_ports {product[58]}]
set_load -pin_load 0.1 [get_ports {product[57]}]
set_load -pin_load 0.1 [get_ports {product[56]}]
set_load -pin_load 0.1 [get_ports {product[55]}]
set_load -pin_load 0.1 [get_ports {product[54]}]
set_load -pin_load 0.1 [get_ports {product[53]}]
set_load -pin_load 0.1 [get_ports {product[52]}]
set_load -pin_load 0.1 [get_ports {product[51]}]
set_load -pin_load 0.1 [get_ports {product[50]}]
set_load -pin_load 0.1 [get_ports {product[49]}]
set_load -pin_load 0.1 [get_ports {product[48]}]
set_load -pin_load 0.1 [get_ports {product[47]}]
set_load -pin_load 0.1 [get_ports {product[46]}]
set_load -pin_load 0.1 [get_ports {product[45]}]
set_load -pin_load 0.1 [get_ports {product[44]}]
set_load -pin_load 0.1 [get_ports {product[43]}]
set_load -pin_load 0.1 [get_ports {product[42]}]
set_load -pin_load 0.1 [get_ports {product[41]}]
set_load -pin_load 0.1 [get_ports {product[40]}]
set_load -pin_load 0.1 [get_ports {product[39]}]
set_load -pin_load 0.1 [get_ports {product[38]}]
set_load -pin_load 0.1 [get_ports {product[37]}]
set_load -pin_load 0.1 [get_ports {product[36]}]
set_load -pin_load 0.1 [get_ports {product[35]}]
set_load -pin_load 0.1 [get_ports {product[34]}]
set_load -pin_load 0.1 [get_ports {product[33]}]
set_load -pin_load 0.1 [get_ports {product[32]}]
set_load -pin_load 0.1 [get_ports {product[31]}]
set_load -pin_load 0.1 [get_ports {product[30]}]
set_load -pin_load 0.1 [get_ports {product[29]}]
set_load -pin_load 0.1 [get_ports {product[28]}]
set_load -pin_load 0.1 [get_ports {product[27]}]
set_load -pin_load 0.1 [get_ports {product[26]}]
set_load -pin_load 0.1 [get_ports {product[25]}]
set_load -pin_load 0.1 [get_ports {product[24]}]
set_load -pin_load 0.1 [get_ports {product[23]}]
set_load -pin_load 0.1 [get_ports {product[22]}]
set_load -pin_load 0.1 [get_ports {product[21]}]
set_load -pin_load 0.1 [get_ports {product[20]}]
set_load -pin_load 0.1 [get_ports {product[19]}]
set_load -pin_load 0.1 [get_ports {product[18]}]
set_load -pin_load 0.1 [get_ports {product[17]}]
set_load -pin_load 0.1 [get_ports {product[16]}]
set_load -pin_load 0.1 [get_ports {product[15]}]
set_load -pin_load 0.1 [get_ports {product[14]}]
set_load -pin_load 0.1 [get_ports {product[13]}]
set_load -pin_load 0.1 [get_ports {product[12]}]
set_load -pin_load 0.1 [get_ports {product[11]}]
set_load -pin_load 0.1 [get_ports {product[10]}]
set_load -pin_load 0.1 [get_ports {product[9]}]
set_load -pin_load 0.1 [get_ports {product[8]}]
set_load -pin_load 0.1 [get_ports {product[7]}]
set_load -pin_load 0.1 [get_ports {product[6]}]
set_load -pin_load 0.1 [get_ports {product[5]}]
set_load -pin_load 0.1 [get_ports {product[4]}]
set_load -pin_load 0.1 [get_ports {product[3]}]
set_load -pin_load 0.1 [get_ports {product[2]}]
set_load -pin_load 0.1 [get_ports {product[1]}]
set_load -pin_load 0.1 [get_ports {product[0]}]
set_load -pin_load 0.1 [get_ports out_vld]
create_clock [get_ports clk]  -period 15.67  -waveform {0 7.835}
set_clock_uncertainty 0.1  [get_clocks clk]
create_generated_clock [get_ports clk_shadow]  -name clk_shadow  -source [get_ports clk]  -edges {1 2 3}  -edge_shift {0.9 0.9 0.9}
set_clock_uncertainty 0.1  [get_clocks clk_shadow]
group_path -name input_grp  -from [list [get_ports clk] [get_ports clk_shadow] [get_ports rst_n]          \
[get_ports in_vld] [get_ports {mcand[63]}] [get_ports {mcand[62]}] [get_ports  \
{mcand[61]}] [get_ports {mcand[60]}] [get_ports {mcand[59]}] [get_ports        \
{mcand[58]}] [get_ports {mcand[57]}] [get_ports {mcand[56]}] [get_ports        \
{mcand[55]}] [get_ports {mcand[54]}] [get_ports {mcand[53]}] [get_ports        \
{mcand[52]}] [get_ports {mcand[51]}] [get_ports {mcand[50]}] [get_ports        \
{mcand[49]}] [get_ports {mcand[48]}] [get_ports {mcand[47]}] [get_ports        \
{mcand[46]}] [get_ports {mcand[45]}] [get_ports {mcand[44]}] [get_ports        \
{mcand[43]}] [get_ports {mcand[42]}] [get_ports {mcand[41]}] [get_ports        \
{mcand[40]}] [get_ports {mcand[39]}] [get_ports {mcand[38]}] [get_ports        \
{mcand[37]}] [get_ports {mcand[36]}] [get_ports {mcand[35]}] [get_ports        \
{mcand[34]}] [get_ports {mcand[33]}] [get_ports {mcand[32]}] [get_ports        \
{mcand[31]}] [get_ports {mcand[30]}] [get_ports {mcand[29]}] [get_ports        \
{mcand[28]}] [get_ports {mcand[27]}] [get_ports {mcand[26]}] [get_ports        \
{mcand[25]}] [get_ports {mcand[24]}] [get_ports {mcand[23]}] [get_ports        \
{mcand[22]}] [get_ports {mcand[21]}] [get_ports {mcand[20]}] [get_ports        \
{mcand[19]}] [get_ports {mcand[18]}] [get_ports {mcand[17]}] [get_ports        \
{mcand[16]}] [get_ports {mcand[15]}] [get_ports {mcand[14]}] [get_ports        \
{mcand[13]}] [get_ports {mcand[12]}] [get_ports {mcand[11]}] [get_ports        \
{mcand[10]}] [get_ports {mcand[9]}] [get_ports {mcand[8]}] [get_ports          \
{mcand[7]}] [get_ports {mcand[6]}] [get_ports {mcand[5]}] [get_ports           \
{mcand[4]}] [get_ports {mcand[3]}] [get_ports {mcand[2]}] [get_ports           \
{mcand[1]}] [get_ports {mcand[0]}] [get_ports {mplier[63]}] [get_ports         \
{mplier[62]}] [get_ports {mplier[61]}] [get_ports {mplier[60]}] [get_ports     \
{mplier[59]}] [get_ports {mplier[58]}] [get_ports {mplier[57]}] [get_ports     \
{mplier[56]}] [get_ports {mplier[55]}] [get_ports {mplier[54]}] [get_ports     \
{mplier[53]}] [get_ports {mplier[52]}] [get_ports {mplier[51]}] [get_ports     \
{mplier[50]}] [get_ports {mplier[49]}] [get_ports {mplier[48]}] [get_ports     \
{mplier[47]}] [get_ports {mplier[46]}] [get_ports {mplier[45]}] [get_ports     \
{mplier[44]}] [get_ports {mplier[43]}] [get_ports {mplier[42]}] [get_ports     \
{mplier[41]}] [get_ports {mplier[40]}] [get_ports {mplier[39]}] [get_ports     \
{mplier[38]}] [get_ports {mplier[37]}] [get_ports {mplier[36]}] [get_ports     \
{mplier[35]}] [get_ports {mplier[34]}] [get_ports {mplier[33]}] [get_ports     \
{mplier[32]}] [get_ports {mplier[31]}] [get_ports {mplier[30]}] [get_ports     \
{mplier[29]}] [get_ports {mplier[28]}] [get_ports {mplier[27]}] [get_ports     \
{mplier[26]}] [get_ports {mplier[25]}] [get_ports {mplier[24]}] [get_ports     \
{mplier[23]}] [get_ports {mplier[22]}] [get_ports {mplier[21]}] [get_ports     \
{mplier[20]}] [get_ports {mplier[19]}] [get_ports {mplier[18]}] [get_ports     \
{mplier[17]}] [get_ports {mplier[16]}] [get_ports {mplier[15]}] [get_ports     \
{mplier[14]}] [get_ports {mplier[13]}] [get_ports {mplier[12]}] [get_ports     \
{mplier[11]}] [get_ports {mplier[10]}] [get_ports {mplier[9]}] [get_ports      \
{mplier[8]}] [get_ports {mplier[7]}] [get_ports {mplier[6]}] [get_ports        \
{mplier[5]}] [get_ports {mplier[4]}] [get_ports {mplier[3]}] [get_ports        \
{mplier[2]}] [get_ports {mplier[1]}] [get_ports {mplier[0]}] [get_ports        \
out_rdy]]
group_path -name output_grp  -to [list [get_ports in_rdy] [get_ports {product[63]}] [get_ports             \
{product[62]}] [get_ports {product[61]}] [get_ports {product[60]}] [get_ports  \
{product[59]}] [get_ports {product[58]}] [get_ports {product[57]}] [get_ports  \
{product[56]}] [get_ports {product[55]}] [get_ports {product[54]}] [get_ports  \
{product[53]}] [get_ports {product[52]}] [get_ports {product[51]}] [get_ports  \
{product[50]}] [get_ports {product[49]}] [get_ports {product[48]}] [get_ports  \
{product[47]}] [get_ports {product[46]}] [get_ports {product[45]}] [get_ports  \
{product[44]}] [get_ports {product[43]}] [get_ports {product[42]}] [get_ports  \
{product[41]}] [get_ports {product[40]}] [get_ports {product[39]}] [get_ports  \
{product[38]}] [get_ports {product[37]}] [get_ports {product[36]}] [get_ports  \
{product[35]}] [get_ports {product[34]}] [get_ports {product[33]}] [get_ports  \
{product[32]}] [get_ports {product[31]}] [get_ports {product[30]}] [get_ports  \
{product[29]}] [get_ports {product[28]}] [get_ports {product[27]}] [get_ports  \
{product[26]}] [get_ports {product[25]}] [get_ports {product[24]}] [get_ports  \
{product[23]}] [get_ports {product[22]}] [get_ports {product[21]}] [get_ports  \
{product[20]}] [get_ports {product[19]}] [get_ports {product[18]}] [get_ports  \
{product[17]}] [get_ports {product[16]}] [get_ports {product[15]}] [get_ports  \
{product[14]}] [get_ports {product[13]}] [get_ports {product[12]}] [get_ports  \
{product[11]}] [get_ports {product[10]}] [get_ports {product[9]}] [get_ports   \
{product[8]}] [get_ports {product[7]}] [get_ports {product[6]}] [get_ports     \
{product[5]}] [get_ports {product[4]}] [get_ports {product[3]}] [get_ports     \
{product[2]}] [get_ports {product[1]}] [get_ports {product[0]}] [get_ports     \
out_vld]]
set_input_delay -clock clk  0.1  [get_ports rst_n]
set_input_delay -clock clk  0.1  [get_ports in_vld]
set_input_delay -clock clk  0.1  [get_ports {mcand[63]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[62]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[61]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[60]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[59]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[58]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[57]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[56]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[55]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[54]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[53]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[52]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[51]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[50]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[49]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[48]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[47]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[46]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[45]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[44]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[43]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[42]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[41]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[40]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[39]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[38]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[37]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[36]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[35]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[34]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[33]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[32]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[31]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[30]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[29]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[28]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[27]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[26]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[25]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[24]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[23]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[22]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[21]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[20]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[19]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[18]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[17]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[16]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[15]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[14]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[13]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[12]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[11]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[10]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[9]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[8]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[7]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[6]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[5]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[4]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[3]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[2]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[1]}]
set_input_delay -clock clk  0.1  [get_ports {mcand[0]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[63]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[62]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[61]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[60]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[59]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[58]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[57]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[56]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[55]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[54]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[53]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[52]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[51]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[50]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[49]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[48]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[47]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[46]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[45]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[44]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[43]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[42]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[41]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[40]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[39]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[38]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[37]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[36]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[35]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[34]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[33]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[32]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[31]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[30]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[29]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[28]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[27]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[26]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[25]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[24]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[23]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[22]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[21]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[20]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[19]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[18]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[17]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[16]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[15]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[14]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[13]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[12]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[11]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[10]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[9]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[8]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[7]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[6]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[5]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[4]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[3]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[2]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[1]}]
set_input_delay -clock clk  0.1  [get_ports {mplier[0]}]
set_input_delay -clock clk  0.1  [get_ports out_rdy]
set_output_delay -clock clk  0.1  [get_ports in_rdy]
set_output_delay -clock clk  0.1  [get_ports {product[63]}]
set_output_delay -clock clk  0.1  [get_ports {product[62]}]
set_output_delay -clock clk  0.1  [get_ports {product[61]}]
set_output_delay -clock clk  0.1  [get_ports {product[60]}]
set_output_delay -clock clk  0.1  [get_ports {product[59]}]
set_output_delay -clock clk  0.1  [get_ports {product[58]}]
set_output_delay -clock clk  0.1  [get_ports {product[57]}]
set_output_delay -clock clk  0.1  [get_ports {product[56]}]
set_output_delay -clock clk  0.1  [get_ports {product[55]}]
set_output_delay -clock clk  0.1  [get_ports {product[54]}]
set_output_delay -clock clk  0.1  [get_ports {product[53]}]
set_output_delay -clock clk  0.1  [get_ports {product[52]}]
set_output_delay -clock clk  0.1  [get_ports {product[51]}]
set_output_delay -clock clk  0.1  [get_ports {product[50]}]
set_output_delay -clock clk  0.1  [get_ports {product[49]}]
set_output_delay -clock clk  0.1  [get_ports {product[48]}]
set_output_delay -clock clk  0.1  [get_ports {product[47]}]
set_output_delay -clock clk  0.1  [get_ports {product[46]}]
set_output_delay -clock clk  0.1  [get_ports {product[45]}]
set_output_delay -clock clk  0.1  [get_ports {product[44]}]
set_output_delay -clock clk  0.1  [get_ports {product[43]}]
set_output_delay -clock clk  0.1  [get_ports {product[42]}]
set_output_delay -clock clk  0.1  [get_ports {product[41]}]
set_output_delay -clock clk  0.1  [get_ports {product[40]}]
set_output_delay -clock clk  0.1  [get_ports {product[39]}]
set_output_delay -clock clk  0.1  [get_ports {product[38]}]
set_output_delay -clock clk  0.1  [get_ports {product[37]}]
set_output_delay -clock clk  0.1  [get_ports {product[36]}]
set_output_delay -clock clk  0.1  [get_ports {product[35]}]
set_output_delay -clock clk  0.1  [get_ports {product[34]}]
set_output_delay -clock clk  0.1  [get_ports {product[33]}]
set_output_delay -clock clk  0.1  [get_ports {product[32]}]
set_output_delay -clock clk  0.1  [get_ports {product[31]}]
set_output_delay -clock clk  0.1  [get_ports {product[30]}]
set_output_delay -clock clk  0.1  [get_ports {product[29]}]
set_output_delay -clock clk  0.1  [get_ports {product[28]}]
set_output_delay -clock clk  0.1  [get_ports {product[27]}]
set_output_delay -clock clk  0.1  [get_ports {product[26]}]
set_output_delay -clock clk  0.1  [get_ports {product[25]}]
set_output_delay -clock clk  0.1  [get_ports {product[24]}]
set_output_delay -clock clk  0.1  [get_ports {product[23]}]
set_output_delay -clock clk  0.1  [get_ports {product[22]}]
set_output_delay -clock clk  0.1  [get_ports {product[21]}]
set_output_delay -clock clk  0.1  [get_ports {product[20]}]
set_output_delay -clock clk  0.1  [get_ports {product[19]}]
set_output_delay -clock clk  0.1  [get_ports {product[18]}]
set_output_delay -clock clk  0.1  [get_ports {product[17]}]
set_output_delay -clock clk  0.1  [get_ports {product[16]}]
set_output_delay -clock clk  0.1  [get_ports {product[15]}]
set_output_delay -clock clk  0.1  [get_ports {product[14]}]
set_output_delay -clock clk  0.1  [get_ports {product[13]}]
set_output_delay -clock clk  0.1  [get_ports {product[12]}]
set_output_delay -clock clk  0.1  [get_ports {product[11]}]
set_output_delay -clock clk  0.1  [get_ports {product[10]}]
set_output_delay -clock clk  0.1  [get_ports {product[9]}]
set_output_delay -clock clk  0.1  [get_ports {product[8]}]
set_output_delay -clock clk  0.1  [get_ports {product[7]}]
set_output_delay -clock clk  0.1  [get_ports {product[6]}]
set_output_delay -clock clk  0.1  [get_ports {product[5]}]
set_output_delay -clock clk  0.1  [get_ports {product[4]}]
set_output_delay -clock clk  0.1  [get_ports {product[3]}]
set_output_delay -clock clk  0.1  [get_ports {product[2]}]
set_output_delay -clock clk  0.1  [get_ports {product[1]}]
set_output_delay -clock clk  0.1  [get_ports {product[0]}]
set_output_delay -clock clk  0.1  [get_ports out_vld]
set_max_delay 15.67  -to [get_ports in_rdy]
set_max_delay 15.67  -to [get_ports {product[63]}]
set_max_delay 15.67  -to [get_ports {product[62]}]
set_max_delay 15.67  -to [get_ports {product[61]}]
set_max_delay 15.67  -to [get_ports {product[60]}]
set_max_delay 15.67  -to [get_ports {product[59]}]
set_max_delay 15.67  -to [get_ports {product[58]}]
set_max_delay 15.67  -to [get_ports {product[57]}]
set_max_delay 15.67  -to [get_ports {product[56]}]
set_max_delay 15.67  -to [get_ports {product[55]}]
set_max_delay 15.67  -to [get_ports {product[54]}]
set_max_delay 15.67  -to [get_ports {product[53]}]
set_max_delay 15.67  -to [get_ports {product[52]}]
set_max_delay 15.67  -to [get_ports {product[51]}]
set_max_delay 15.67  -to [get_ports {product[50]}]
set_max_delay 15.67  -to [get_ports {product[49]}]
set_max_delay 15.67  -to [get_ports {product[48]}]
set_max_delay 15.67  -to [get_ports {product[47]}]
set_max_delay 15.67  -to [get_ports {product[46]}]
set_max_delay 15.67  -to [get_ports {product[45]}]
set_max_delay 15.67  -to [get_ports {product[44]}]
set_max_delay 15.67  -to [get_ports {product[43]}]
set_max_delay 15.67  -to [get_ports {product[42]}]
set_max_delay 15.67  -to [get_ports {product[41]}]
set_max_delay 15.67  -to [get_ports {product[40]}]
set_max_delay 15.67  -to [get_ports {product[39]}]
set_max_delay 15.67  -to [get_ports {product[38]}]
set_max_delay 15.67  -to [get_ports {product[37]}]
set_max_delay 15.67  -to [get_ports {product[36]}]
set_max_delay 15.67  -to [get_ports {product[35]}]
set_max_delay 15.67  -to [get_ports {product[34]}]
set_max_delay 15.67  -to [get_ports {product[33]}]
set_max_delay 15.67  -to [get_ports {product[32]}]
set_max_delay 15.67  -to [get_ports {product[31]}]
set_max_delay 15.67  -to [get_ports {product[30]}]
set_max_delay 15.67  -to [get_ports {product[29]}]
set_max_delay 15.67  -to [get_ports {product[28]}]
set_max_delay 15.67  -to [get_ports {product[27]}]
set_max_delay 15.67  -to [get_ports {product[26]}]
set_max_delay 15.67  -to [get_ports {product[25]}]
set_max_delay 15.67  -to [get_ports {product[24]}]
set_max_delay 15.67  -to [get_ports {product[23]}]
set_max_delay 15.67  -to [get_ports {product[22]}]
set_max_delay 15.67  -to [get_ports {product[21]}]
set_max_delay 15.67  -to [get_ports {product[20]}]
set_max_delay 15.67  -to [get_ports {product[19]}]
set_max_delay 15.67  -to [get_ports {product[18]}]
set_max_delay 15.67  -to [get_ports {product[17]}]
set_max_delay 15.67  -to [get_ports {product[16]}]
set_max_delay 15.67  -to [get_ports {product[15]}]
set_max_delay 15.67  -to [get_ports {product[14]}]
set_max_delay 15.67  -to [get_ports {product[13]}]
set_max_delay 15.67  -to [get_ports {product[12]}]
set_max_delay 15.67  -to [get_ports {product[11]}]
set_max_delay 15.67  -to [get_ports {product[10]}]
set_max_delay 15.67  -to [get_ports {product[9]}]
set_max_delay 15.67  -to [get_ports {product[8]}]
set_max_delay 15.67  -to [get_ports {product[7]}]
set_max_delay 15.67  -to [get_ports {product[6]}]
set_max_delay 15.67  -to [get_ports {product[5]}]
set_max_delay 15.67  -to [get_ports {product[4]}]
set_max_delay 15.67  -to [get_ports {product[3]}]
set_max_delay 15.67  -to [get_ports {product[2]}]
set_max_delay 15.67  -to [get_ports {product[1]}]
set_max_delay 15.67  -to [get_ports {product[0]}]
set_max_delay 15.67  -to [get_ports out_vld]
set_resistance 0  [get_nets rst_n]
